#!/usr/bin/env bash

source "$(dirname `realpath $0`)/../lib/clear_notification"
source "$(dirname `realpath $0`)/../lib/update_notification"

function check-notification() {
	[[ $# -ne 2 ]] && return 4

	for tdx in $(seq 0 1 3)
	do
		update-notification "$1" "$2"
		sleep 1
	done

	clear-notification "$ID"
	return $?
}
