#!/usr/bin/env bash


function playback-notification() {
	[[ $# -ne 2 ]] && return 4

	local status=`cat ${1}/STATUS`

	if [[ "$status" == "playing" ]]
	then
		mpc pause &>/dev/null &
		update-notification "${1}" "${2}"
	elif [[ "$status" == "paused" ]]
	then
		mpc play &>/dev/null & 
		check-notification "$1" "$2" &
	else
		dunstify -r "$2" -h int:id:$2 -u critical "Failed:" "MPD is neither playing nor paused."
	fi
}
